version: '3.3'

services:
  db:
    image: postgres:13-alpine
    restart: always
    env_file: .env
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - 5432:5432

